spring:
  application:
    name: ksis-be

  datasource:
    url: jdbc:mysql://localhost:3306/crawl
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  batch:
    job:
      enabled: false

jwt:
  secret: "newyourjwtsecretkeythatisatleast256bitslongandbase64encodedexample1234567890123456789012345678901234567890newyourjwtsecretkeythatisatleast256bitslongandbase64encodedexample1234567890123456789012345678901234567890"